In [1]:
import numpy as np

In [2]:
a = np.array([1,5,10])
print(a)

[ 1  5 10]


In [3]:
b = np.array([[1,7,20], [5, 8, 9]])
print(b)

[[ 1  7 20]
 [ 5  8  9]]



We use ndim to find out the size of the directory:

In [4]:
b.ndim

2

In [5]:
a.ndim

1

In [6]:
#shape is used to find out the size of our 2 row and 3 column array:

b.shape


(2, 3)

In [7]:
a.dtype

dtype('int32')

In [8]:
x = np.array([1.0,5.4,10.42])
x.dtype

dtype('float64')

We use row and column numbers to access a specific cell of the array:

In [9]:
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [10]:
b[0,2]

20

In [11]:
b[1,1]

8

In [12]:
b[0]

array([ 1,  7, 20])

We use : to access the second and third elements in the first row - namely 7 and 20:

In [13]:
b[0, 1:]

array([ 7, 20])

In [14]:
b[1, 1] = 18
b[1, 1]

18

In [15]:
b

array([[ 1,  7, 20],
       [ 5, 18,  9]])

<H3> Automatic array creation </H3>

In [16]:
# All zero matrix/array
array_z = np.zeros((2,3))
array_z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# Array with all the same value
array1= np.full((4,4), 50)
array1

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [18]:
# Random array creation
array2 = np.random.rand(4,3)
array2

array([[0.7313626 , 0.0503504 , 0.79402403],
       [0.93638925, 0.35361886, 0.76084139],
       [0.29519808, 0.72149397, 0.80665813],
       [0.70917101, 0.91324661, 0.96432848]])

In [19]:
#automatic random int array creation
array3 = np.random.randint(0,100,size=(5,5))
array3

array([[73, 31, 43, 83, 29],
       [70, 87, 83, 24, 17],
       [24, 68, 25, 70, 65],
       [45, 25, 12, 66, 63],
       [ 3, 55, 16, 20, 11]])

<H3> Be careful when copying strings!!! </H3>

In [21]:

a = np.array([1,2,3])
b = a
b[0] = 90

print(a)

[90  2  3]


In [22]:
# b, like a pointer, points to the same memory location as a, so the change in b! also occurs in a.
# To avoid such situations, use the copy() function:
a = np.array([1,2,3])
b = a.copy()
b[0] = 90

print(a)

[1 2 3]


In [23]:
print(b)

[90  2  3]


<H3> Mathematical Operations on Arrays </H3>

In [24]:

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [25]:

a + 4

array([5, 6, 7, 8])

In [26]:
a * 2

array([2, 4, 6, 8])

In [27]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [28]:

b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [29]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)


<H3> Statistics </H3>

In [30]:
array4 = np.array([[1,2,3],[4,5,6]])
array4

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.min(array4)

1

In [34]:
np.max(array4)

6

In [35]:

np.sum(array4)

21

<H3> Loading array from file </H3>

In [36]:
filedata = np.genfromtxt('example.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[1 2 3 4 5 6 7]
 [8 9 7 8 9 9 7]
 [3 3 5 6 5 4 0]]


In [37]:
filedata[1,0]

8